"""
Main Flask to OpenBB Converter Class

This module contains the primary conversion logic that orchestrates the transformation
of Flask applications into OpenBB-compatible extensions.
"""

from typing import Dict, List, Any, Optional
from flask import Flask
from .introspection import FlaskRouteIntrospector
from .generators import ProviderGenerator, RouterGenerator, ModelGenerator


class FlaskToOpenBBConverter:
    """
    Main converter class that transforms Flask applications into OpenBB extensions.
    
    This class serves as the primary interface for converting existing Flask applications
    into OpenBB-compatible providers, routers, and data models.
    
    Example:
        >>> from flask import Flask
        >>> from flask_to_openbb_converter import FlaskToOpenBBConverter
        >>> 
        >>> app = Flask(__name__)
        >>> converter = FlaskToOpenBBConverter(app)
        >>> provider_code = converter.generate_provider_code()
        >>> router_code = converter.generate_router_code()
    """
    
    def __init__(self, flask_app: Flask, provider_name: Optional[str] = None):
        """
        Initialize the converter with a Flask application instance.
        
        Args:
            flask_app: The Flask application instance to convert
            provider_name: Optional custom name for the generated provider
        """
        self.flask_app = flask_app
        self.provider_name = provider_name or self._generate_provider_name()
        
        # Initialize introspection and generation components
        self.introspector = FlaskRouteIntrospector(flask_app)
        self.provider_generator = ProviderGenerator(self.provider_name)
        self.router_generator = RouterGenerator(self.provider_name)
        self.model_generator = ModelGenerator()
        
        # Analyze the Flask app
        self.routes_info = self.introspector.analyze_routes()
        
    def _generate_provider_name(self) -> str:
        """Generate a provider name from the Flask app name."""
        app_name = getattr(self.flask_app, 'name', 'flask_app')
        # Convert to snake_case and add suffix
        provider_name = app_name.lower().replace('-', '_').replace(' ', '_')
        return f"{provider_name}_provider"
    
    def generate_provider_code(self) -> str:
        """
        Generate OpenBB Provider code from Flask routes.
        
        Returns:
            String containing the complete provider module code
        """
        return self.provider_generator.generate_from_routes(self.routes_info)
    
    def generate_router_code(self) -> str:
        """
        Generate OpenBB Router code from Flask routes.
        
        Returns:
            String containing the complete router module code
        """
        return self.router_generator.generate_from_routes(self.routes_info)
    
    def generate_models_code(self) -> Dict[str, str]:
        """
        Generate Pydantic model code from Flask route responses.
        
        Returns:
            Dictionary mapping model names to their code
        """
        return self.model_generator.generate_from_routes(self.routes_info)
    
    def generate_complete_extension(self) -> Dict[str, str]:
        """
        Generate a complete OpenBB extension from the Flask app.
        
        Returns:
            Dictionary containing all generated files:
            - provider/__init__.py
            - router/__init__.py  
            - models/*.py
            - pyproject.toml
            - README.md
        """
        extension_files = {}
        
        # Generate core components
        extension_files['provider/__init__.py'] = self.generate_provider_code()
        extension_files['router/__init__.py'] = self.generate_router_code()
        
        # Generate models
        models = self.generate_models_code()
        for model_name, model_code in models.items():
            extension_files[f'models/{model_name}.py'] = model_code
        
        # Generate configuration files
        extension_files['pyproject.toml'] = self._generate_pyproject_toml()
        extension_files['README.md'] = self._generate_readme()
        
        return extension_files
    
    def _generate_pyproject_toml(self) -> str:
        """Generate pyproject.toml for the converted extension."""
        return f'''[tool.poetry]
name = "openbb-{self.provider_name.replace('_', '-')}"
version = "1.0.0"
description = "OpenBB extension converted from Flask application"
authors = ["Generated by Flask-to-OpenBB Converter"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11,<3.14"
openbb = "^4.3.0"
openbb-core = "^1.4.8"
pandas = "^2.0.0"
requests = "^2.31.0"
pydantic = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
'''
    
    def _generate_readme(self) -> str:
        """Generate README.md for the converted extension."""
        return f'''# {self.provider_name.title()} OpenBB Extension

This OpenBB extension was automatically generated from a Flask application using the Flask-to-OpenBB Converter.

## Installation

```bash
pip install openbb-{self.provider_name.replace('_', '-')}
```

## Usage

```python
from openbb import obb

# Use the converted endpoints
result = obb.{self.provider_name.replace('_provider', '')}.<endpoint_name>()
```

## Original Flask Routes Converted

{self._generate_routes_documentation()}

## Generated by Flask-to-OpenBB Converter
- Conversion Date: {self._get_current_timestamp()}
- Original Flask App: {self.flask_app.name}
'''
    
    def _generate_routes_documentation(self) -> str:
        """Generate documentation for converted routes."""
        docs = []
        for route_info in self.routes_info:
            docs.append(f"- `{route_info['rule']}` → `obb.{self.provider_name.replace('_provider', '')}.{route_info['function_name']}()`")
        return '\n'.join(docs)
    
    def _get_current_timestamp(self) -> str:
        """Get current timestamp for documentation."""
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")