[tool.poetry]
name = "openbb-flask-adapter"
version = "0.1.0"
description = "Flask application adapter for OpenBB Platform"
authors = ["Boris Li <boris.quan.li@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "openbb_flask_adapter" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
openbb-core = "^1.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
flask_adapter = "openbb_flask_adapter.flask_router:router"
